### ISSUE TITLE
SNAPSHOT-Release

### ISSUE THREAD

**Issue by mydeadlyvenoms** [project-aries/docker-java-shaded#1]
First of all, great project!
This one is really handy in many situations. 
I tried to get docker-java running inside a GlassFish / Payara environment and had a pretty hard time doing so.
It would be great if you could provide kind of a shaded SNAPSHOT release because the current SNAPSHOT of docker-java already implemented support for services.

Thank you very much in advance.

**Comment by cdancy** [comment]
@mydeadlyvenoms I'd prefer not to as I don't want to invest too much time into this project as honestly those guys should be doing this.

With that said ... they are pretty good about spinning up a new release if you need it. I've asked them a handful of times over the past year and they usually knock out a new point release within a matter of days.

**Comment by cdancy** [comment]
And of course, if they do that, I can knock one out here easily enough.

**Comment by mydeadlyvenoms** [comment]
Thank you for your response, I can absolutely understand.
Let's create an issue and see what happens :-)

**Comment by mydeadlyvenoms** [comment]
Well that was fast: https://github.com/docker-java/docker-java/releases

**Comment by cdancy** [comment]
@mydeadlyvenoms let me try to kick a release and see what happens. Sometimes jcenter is finicky about the types of versions it will host publicly.

**Comment by cdancy** [comment]
@mydeadlyvenoms it's not publicly hosted anywhere that I can find :(

**Comment by mydeadlyvenoms** [comment]
Same here :-(, lets see if the docker-java guys can push it to maven central.

**Comment by mydeadlyvenoms** [comment]
Hi @cdancy 
RC2 seems to be ready now: https://mvnrepository.com/artifact/com.github.docker-java/docker-java/3.1.0-rc-2

Thank you very much for your help!

**Comment by mydeadlyvenoms** [comment]
Hi @cdancy how are you doing?
Do you have any updates on this? If I can be of assistance, please do not hesitate to contact me.

**Comment by cdancy** [comment]
@mydeadlyvenoms didn't want to do this as I only wanted to focus on actual releases (not snapshot or rc's) but I went ahead and knocked it out anyway. Had to massage the release scripts a bit to make it work which was good in that I found some bugs.

In either event `3.1.0-rc-2` should be good to go now.

**Comment by mydeadlyvenoms** [comment]
@cdancy thank you very much, works! :-)
